### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asgs**
Minor MD changes.

### CODE REVIEW

**Comment by amanteaux** [comment]
Thank you for your interest in Plume Framework.

I am not sure about you made in the README.md. It looks like you have mainly changed the formating of the text. 
Can you explain your pull request?

**Comment by asgs** [comment]
@amanteaux yes, that's right. it's a few formatting changes + MD changes plus few typo fixes.

**Comment by amanteaux** [comment]
Can you revert the line break changes?
Actually these line breaks enables to often keep lines length under 100 characters: that is easier to read in an IDE.
Moreover, changing the line breaks complicate the work of reviewing your changes.

**Comment by asgs** [comment]
It's a normal practice to enable soft-wrapping in your IDE after 80/100 characters. I don't think adding manual line breaks is a best practice here.

**Comment by amanteaux** [comment]
Humm... I do not really agree with you here.
I do not think there is a best practice here: https://stackoverflow.com/questions/29955688/in-markdown-is-there-an-official-best-practice-as-relates-to-line-length

Moreover it is a common practice to avoid formatting code/text you have not written when you make a pull request.

**Comment by asgs** [comment]
Yes, that's allowed, but the usage of "hard-wrapping" in this case seems to be allowing better readability on IDEs which is certainly an option that every IDE provides.

Moreover, this pull request is mainly meant to FORMAT the markdown file so that such hard linebreaks are no more there, so it's not an accidental reformatting or such.

**Pull request closed without merging**
